using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using TeslaSQL.DataUtils;

namespace TeslaSQL.Agents {
    /// <summary>
    /// This agent sends alerts that are generated by other agents.
    /// </summary>
    class Notifier : Agent {
        private IEmailClient emailClient;

        //base keyword invokes the base class's constructor
        public Notifier(IDataUtils dataUtils, IEmailClient emailClient, Logger logger)
            : base(dataUtils, null, logger) {
            this.emailClient = emailClient;
        }

        public override void ValidateConfig() {
            Config.ValidateRequiredHost(Config.relayServer);
            if (Config.relayType == SqlFlavor.None) {
                throw new Exception("Notifier agent requires a valid SQL flavor for relay");
            }
        }

        public override void Run() {
            var errors = sourceDataUtils.GetUnsentErrors();
            var errorList = new List<string>();
            var ids = new List<int>();
            foreach (DataRow row in errors.Rows) {
                errorList.Add(row.Field<string>("CelError"));
                ids.Add(row.Field<int>("CelId"));
            }
            if (errorList.Count == 0) {
                return;
            }
            emailClient.SendEmail(Config.emailErrorRecipient, "Errors occurred during changetracking", string.Join("\r\n", errorList));
            sourceDataUtils.MarkErrorsSent(ids);
        }
    }
}
