using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TeslaSQL.Agents
{
    /// <summary>
    /// This agent sends alerts that are generated by other agents.
    /// </summary>
    class Notifier : Agent
    {

        //base keyword invokes the base class's constructor
        public Notifier(Config config, IDataUtils dataUtils) : base(config, dataUtils) {

        }
        
        public override void ValidateConfig()
        {
            config.ValidateRequiredHost(config.relayServer);
            if (config.relayType == null) {
                throw new Exception("Notifier agent requires a valid SQL flavor for relay");
            }
        }

        public override void Run()
        {
            throw new NotImplementedException();
        }
    }
}
